revision = 'a_first_migration'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_language_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_language_profiles', ['current_language_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_language_profile_id')
    # ### end Alembic commands ###
